producer/config/routes.rb
Producer::Application.routes.draw do

  resources :categories

  get "pages/index"

  resources :posts do
    resources :comments, :only => [:create]
  end

end

producer/app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name

  validates_presence_of :name
end

producer/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  attr_accessible :author, :body, :email, :url

  validates_presence_of :body, :post
  validates_associated :post

  validates_format_of :email, :allow_blank => true,
  :with => /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{1,3})+$/
  validates_format_of :url, :allow_blank => true,
  :with => /^(https?:\/\/)?(www\.)?([a-zA-Z0-9_\-]+)+\.([a-zA-Z]{2,4})/
end

producer/app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :excerpt, :title, :author_id

  validates_presence_of :title, :body, :author
  validates_associated :author

  has_many :comments, :dependent => :destroy
  belongs_to :author, class_name: "User", foreign_key: "author_id"
  has_and_belongs_to_many :categories
end

producer/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :first_name, :last_name

  has_many :posts, foreign_key: "author_id"

  validates_presence_of :email, :first_name, :last_name
  validates_uniqueness_of :email
  validates_format_of :email,
  :with => /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{1,3})+$/

  def full_name
    "#{ first_name } #{ last_name }".titleize
  end

end

producer/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  respond_to :json, :html, :xml
end

producer/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

producer/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # POST /comments
  # POST /comments.json
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(params[:comment])
    flash[:alert] = 'Fail to receive the comment. Double check de fields.' unless
      @comment.save!

    redirect_to @post
  end
end

producer/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

producer/app/controllers/posts_controller.rb
 class PostsController < ApplicationController
  before_filter :load_resources, only: %w(new create edit update)
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    respond_with @posts
  end
  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    respond_with @post
  end
  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new
    respond_with @post
  end
  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end
  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])
    flash[:notice] = 'Post was successfully created. ' if @post.save
    respond_with @post
  end
  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])
    flash[:notice] = 'Post was successfully updated. ' if
      @post.update_attributes(params[:post])
    respond_with @post
  end
  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @posts = Post.find(params[:id])
    @posts.destroy
    respond_with @posts
  end

  private

  def load_resources
    @authors = User.all
    @categories = Category.all
  end
end

producer/app/helpers/application_helper.rb
module ApplicationHelper

  def flash_messages
    flash.collect do |key, msg|
      content_tag :p, msg, id: key, class: "flash_message"
    end.join.html_safe
  end

  def error_messages_for(resource)
    render partial: "shared/error_messages", locals: { resource: @post }
  end

end

producer/app/helpers/categories_helper.rb
module CategoriesHelper
end

producer/app/helpers/comments_helper.rb
module CommentsHelper
end

producer/app/helpers/pages_helper.rb
module PagesHelper
end

producer/app/helpers/posts_helper.rb
module PostsHelper
end

producer/app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>

  <%= error_messages_for @category %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

producer/app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

producer/app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

producer/app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

producer/app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

producer/app/views/comments/_comment.html.erb
<%= div_for comment do %>
  <p>
    <%= comment.author %><br />
    <%= comment.body %><br />
    Posted <%= time_ago_in_words comment.created_at %> ago<br />
  </p>
<% end %>

producer/app/views/comments/_form.html.erb
<%= form_for [post, comment] do |f| %>
  <%= error_messages_for comment %>

  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>

  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

producer/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Producer</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= flash_messages %>
<%= yield %>

</body>
</html>

producer/app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

producer/app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>

  <%= error_messages_for @post %>

  <div class="field">
    <%= f.label :author_id, "Author" %><br />
    <%= f.collection_select :author_id, @authors, :id, :full_name %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title, :size => 50 %>
  </div>
  <div class="field">
    <%= f.label :excerpt %><br />
    <%= f.text_area :excerpt, :rows => 10, :cols => 80 %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body, :rows => 50, :cols => 80 %>
  </div>
  <div class="field">
    <% @categories.each do |c| %>
      <%= label_tag do %>
        <%= check_box_tag "post[category_ids][]", c.id, @post.categories.include?(c) %>
        <%= c.name %><br />
      <% end %>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

producer/app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

producer/app/views/posts/index.html.erb
<% if @posts.present? %>

  <% @posts.each do |post| %>
    <h2><%= link_to post.title.titleize, post %></h2>

    <div id="post">
      <%= post.excerpt %>
      <p><%= link_to "continue ...", post %></p>
    </div>

    <p>
      <%= link_to "Edit", edit_post_path(post) %>
      <%= link_to "Destroy", post, :confirm => 'Are you sure?',
        :method => :delete %>
    </p>

    <hr />
  <% end %>

<% else %>
  <p>We'll start posting soon.</p>
<% end %>

<p><%= link_to 'New Post', new_post_path %></p>

producer/app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

producer/app/views/posts/show.html.erb
<h2><%= @post.title %></h2>

<div id="post">
  <%= @post.body %>
</div>

<hr />

<h3>Comments</h3>

<div id="comments">
  <% if @post.comments.any? %>
    <%= render @post.comments %>
  <% else %>
      <p>Nobody commented this post yet.</p>
  <% end %>
</div>

<hr />

<%= render "comments/form", post: @post, comment: Comment.new %>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

producer/app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(resource.errors.count, "error") %> prohibited this post from being saved:</h2>

    <ul>
    <% resource.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>